# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert string into string vector
#' 
#' @param str A string to be converted. 
#' @param len Dividing length of string. 
#' @export
str2strvec <- function(str, len = 1L) {
    .Call(`_wameicheckr_str2strvec`, str, len)
}

#' Editing distance (Levenshtein distance) of two string vectors
#' 
#' @param str1 A string to be compared. 
#' @param str2 A string to be compared. 
#' @param len Dividing length of string. 
#' @export
editdist <- function(s1, s2, len = 1L) {
    .Call(`_wameicheckr_editdist`, s1, s2, len)
}

